// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// choose_int
int choose_int(int n, int k);
RcppExport SEXP _rcpplong_choose_int(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(choose_int(n, k));
    return rcpp_result_gen;
END_RCPP
}
// choose_long
long int choose_long(int n, int k);
RcppExport SEXP _rcpplong_choose_long(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(choose_long(n, k));
    return rcpp_result_gen;
END_RCPP
}
// accumulate_long
long int accumulate_long(long int n);
RcppExport SEXP _rcpplong_accumulate_long(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(accumulate_long(n));
    return rcpp_result_gen;
END_RCPP
}
// accumulate_mat
NumericMatrix accumulate_mat(long int n);
RcppExport SEXP _rcpplong_accumulate_mat(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(accumulate_mat(n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcpplong_choose_int", (DL_FUNC) &_rcpplong_choose_int, 2},
    {"_rcpplong_choose_long", (DL_FUNC) &_rcpplong_choose_long, 2},
    {"_rcpplong_accumulate_long", (DL_FUNC) &_rcpplong_accumulate_long, 1},
    {"_rcpplong_accumulate_mat", (DL_FUNC) &_rcpplong_accumulate_mat, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rcpplong(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
