# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname choose
choose_int <- function(n, k) {
    .Call('_rcpplong_choose_int', PACKAGE = 'rcpplong', n, k)
}

#' @rdname choose
choose_long <- function(n, k) {
    .Call('_rcpplong_choose_long', PACKAGE = 'rcpplong', n, k)
}

