# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname choose_rcpp
#' @export
choose_int <- function(n, k) {
    .Call('_rcpplong_choose_int', PACKAGE = 'rcpplong', n, k)
}

#' @rdname choose_rcpp
#' @export
choose_long <- function(n, k) {
    .Call('_rcpplong_choose_long', PACKAGE = 'rcpplong', n, k)
}

#' @rdname accumulate_rcpp
#' @export
accumulate_long <- function(n) {
    .Call('_rcpplong_accumulate_long', PACKAGE = 'rcpplong', n)
}

#' @rdname accumulate_rcpp
#' @export
accumulate_mat <- function(n) {
    .Call('_rcpplong_accumulate_mat', PACKAGE = 'rcpplong', n)
}

